### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by samiralavi** [ORNL/dasp-stacker#2]
There is no documentation that describes the available APIs and modules. The example notebooks are helpful, but a separate API documentation is needed. It could be added to the `README.md` file of the repo.

**Comment by jcupsmith** [comment]
@samiralavi I have added this documentation to the `README.md` file, please take a look to make sure this covers what you are requesting. Thank you for your patience, I wasn't able to get to this until this week.

**Comment by samiralavi** [comment]
Great work, @jcupsmith. It looks perfect. I am sure this will make it considerably easier for the community to use your library.
