### ISSUE TITLE
Example notebook error

### ISSUE THREAD

**Issue by samiralavi** [ORNL/dasp-stacker#4]
I was able to install the Python package both from PyPi and from the repo successfully. However, when running the example notebooks, I found that the `algorithm_walkthrough.ipynb` has issues. The function `sin_creator` is not defined. Looking at the other example, it seems the name has been misspelt and the correct one should be `sine_wave_creator`.

**Comment by jcupsmith** [comment]
@samiralavi I believe I have fixed all of the issues within the algorithm_walkthrough.ipynb file. Just let me know if something is still causing errors for you or if it seems good to go!

**Comment by samiralavi** [comment]
Thanks @jcupsmith, it is good now.
